# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

update_omega <- function(n, K, whichik, xbetak, zgammak) {
    .Call(`_pgmultinomr_update_omega`, n, K, whichik, xbetak, zgammak)
}

fillMatrix <- function(a) {
    .Call(`_pgmultinomr_fillMatrix`, a)
}

return_pgdraw <- function(b, c) {
    .Call(`_pgmultinomr_return_pgdraw`, b, c)
}

rcpp_pgdraw <- function(b, c) {
    .Call(`_pgmultinomr_rcpp_pgdraw`, b, c)
}

rcpparma_hello_world <- function() {
    .Call(`_pgmultinomr_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_pgmultinomr_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_pgmultinomr_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_pgmultinomr_rcpparma_bothproducts`, x)
}

update_beta <- function(k, ok, yk, xk, wgam, betaVarInverse, betaMean) {
    .Call(`_pgmultinomr_update_beta`, k, ok, yk, xk, wgam, betaVarInverse, betaMean)
}

update_gamma <- function(k, ok, yk, wk, xbet, gammaVarInverse, gammaMean) {
    .Call(`_pgmultinomr_update_gamma`, k, ok, yk, wk, xbet, gammaVarInverse, gammaMean)
}

update_beta_logistic <- function(omega, kappa, x, wgamma, betaVarInverse, betaMean) {
    .Call(`_pgmultinomr_update_beta_logistic`, omega, kappa, x, wgamma, betaVarInverse, betaMean)
}

update_gamma_logistic <- function(omega, kappa, w, xbeta, gammaVarInverse, gammaMean) {
    .Call(`_pgmultinomr_update_gamma_logistic`, omega, kappa, w, xbeta, gammaVarInverse, gammaMean)
}

make_xbeta <- function(x, beta) {
    .Call(`_pgmultinomr_make_xbeta`, x, beta)
}

